#!/usr/bin/env python3
"""mksites.py — build sites.txt (and sites.inc) from BMF.c.

One row per function body Hex-Rays emitted:

    <VA>\t<name>\t<convention>\t<first line>\t<last line>

The spans come from Hex-Rays' own `//----- (004XXXXX) ------` banners, not
from a scan for definition lines.  That distinction is the whole reason this
script exists: a definition-line regex misses every `__usercall`/`__userpurge`
function, because those are printed as `sub_4022C0@<eax>(…)` — the name is
followed by `@`, not by `(` — and the *preceding* function's span then runs on
and swallows the missed body whole.  38 of 151 functions were invisible that
way, and one generated `.inc` held ten concatenated bodies.

sites.inc is the same table as a C initialiser list for trace32.cpp.

Usage: mksites.py [BMF.c]
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

BANNER = re.compile(r'^//-+\s*\(([0-9A-Fa-f]{6,8})\)\s*-+\s*$')
# The definition line: starts with a type name (so a `#error` Hex-Rays emitted
# in place of a body it could not analyse is skipped), and runs up to the
# function name, which is followed either by '(' or — for __usercall and
# __userpurge — by the '@<reg>' return annotation.
DEFN = re.compile(r'^[A-Za-z_][^;]*?\b([A-Za-z_]\w*)\s*(?:@<\w+>\s*)?\(')
CONVS = ('usercall', 'userpurge', 'thiscall', 'fastcall', 'stdcall', 'cdecl')


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, 'BMF.c')
    lines = open(src, errors='replace').read().split('\n')

    banners = [(i, m.group(1)) for i, l in enumerate(lines)
               for m in [BANNER.match(l)] if m]
    rows, skipped = [], []
    for k, (i, va) in enumerate(banners):
        end = (banners[k + 1][0] if k + 1 < len(banners) else len(lines)) - 1
        # The definition is the first non-blank, non-comment line after the
        # banner; trim trailing blanks and the next banner's lead-in.
        j = i + 1
        while j <= end and (not lines[j].strip() or lines[j].lstrip().startswith('//')):
            j += 1
        m = DEFN.match(lines[j]) if j <= end else None
        if not m:
            skipped.append((va, lines[j].strip()[:70] if j <= end else '<empty>'))
            continue
        while end > j and not lines[end].strip():
            end -= 1
        conv = next((c for c in CONVS if '__' + c in lines[j]), 'cdecl')
        rows.append((int(va, 16), m.group(1), conv, j + 1, end + 1))

    rows.sort()
    with open(os.path.join(HERE, 'sites.txt'), 'w') as f:
        for va, name, conv, a, b in rows:
            f.write(f"{va:08X}\t{name}\t{conv}\t{a}\t{b}\n")
    with open(os.path.join(HERE, 'sites.inc'), 'w') as f:
        f.write("// Generated by mksites.py from BMF.c — do not edit.\n")
        for va, name, conv, a, b in rows:
            f.write(f'  {{0x{va:08X}, "{name}", "{conv}", 0, 0}},\n')

    print(f"banners {len(banners)}  parsed {len(rows)}  unparsable {len(skipped)}")
    for va, txt in skipped:
        print(f"   {va}: {txt}")
    counts = {}
    for _, _, c, _, _ in rows:
        counts[c] = counts.get(c, 0) + 1
    print("by convention:", sorted(counts.items(), key=lambda kv: -kv[1]))


if __name__ == '__main__':
    main()
