#!/usr/bin/env python3
"""mkdata.py — carve BMF.exe's *data* out of the PE, for the standalone build.

The moved bodies reach their globals by absolute address — `*(int *)0x00441040`
— because that is what the decompilation says and rewriting 845 of them into
named objects would be a much bigger change than it sounds: the same address is
an `int` to one function and a `char[]` to the next (incdec.md §6.1), several
are read at offsets Hex-Rays never named, and some are only reachable as
`&x + n`.  Keeping the addresses means the bodies do not have to change at all.

So the standalone binary carries BMF's initialised data, mapped at the original
virtual addresses, and runs none of its code.  Three sections matter:

    .rdata  0x00438000  0x8554   constants, string literals, the IAT
    .data   0x00441000  0x6518   mutable state (raw is 0x1A00; the rest is bss)
    .trace  0x00448000  0x164

.text is *not* included.  The two places that need something from it are
handled in crt.cpp: sub_402E30, which is `push 7; call exit_402E40` and is
reimplemented in C, and the statically-linked CRT, which is replaced wholesale.

Output is one assembler file with the bytes and a linker-placed section, plus
a header of the extents so build.sh can pass --section-start.
"""
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
EXE = os.path.join(HERE, '..', '..', '..', 'exe32', 'BMF.exe')
WANT = ('.rdata', '.data', '.trace')


def sections(d):
    pe = struct.unpack_from('<I', d, 0x3c)[0]
    nsec = struct.unpack_from('<H', d, pe + 6)[0]
    optsz = struct.unpack_from('<H', d, pe + 20)[0]
    base = struct.unpack_from('<I', d, pe + 0x34)[0]
    out = []
    for i in range(nsec):
        o = pe + 24 + optsz + i * 40
        name = d[o:o + 8].rstrip(b'\0').decode()
        vsize, va, rawsize, rawptr = struct.unpack_from('<IIII', d, o + 8)
        out.append((name, base + va, vsize, d[rawptr:rawptr + rawsize]))
    return out


def main():
    exe = sys.argv[1] if len(sys.argv) > 1 else EXE
    d = open(exe, 'rb').read()
    secs = [s for s in sections(d) if s[0] in WANT]
    if len(secs) != len(WANT):
        sys.exit('missing sections: %s' % [s[0] for s in secs])
    secs.sort(key=lambda s: s[1])

    lo = secs[0][1]
    hi = max(va + vsize for _n, va, vsize, _r in secs)
    # One contiguous image, gaps zero-filled: the sections are page-aligned in
    # the PE and the holes between them are never referenced, but a single
    # section is one --section-start instead of three and cannot drift.
    img = bytearray(hi - lo)
    for name, va, vsize, raw in secs:
        img[va - lo:va - lo + min(len(raw), vsize)] = raw[:vsize]

    out = os.path.join(HERE, 'bmfdata.S')
    with open(out, 'w') as f:
        f.write('/* Generated by mkdata.py from BMF.exe.  Do not edit.\n'
                ' *\n'
                ' * BMF\'s .rdata/.data/.trace, to be placed at %08X by the\n'
                ' * linker.  Writable: the PE\'s .rdata holds the import table,\n'
                ' * whose slots the standalone build fills in at startup, and\n'
                ' * marking one section rather than three keeps the placement to\n'
                ' * a single --section-start.\n'
                ' */\n' % lo)
        f.write('\t.section .bmfdata,"aw",@progbits\n')
        f.write('\t.globl __bmf_data_start\n__bmf_data_start:\n')
        for i in range(0, len(img), 32):
            f.write('\t.byte ' + ','.join(str(b) for b in img[i:i + 32]) + '\n')
        f.write('\t.globl __bmf_data_end\n__bmf_data_end:\n')

    with open(os.path.join(HERE, 'bmfdata.mk'), 'w') as f:
        f.write('BMFDATA_START = 0x%08X\n' % lo)
        f.write('BMFDATA_END   = 0x%08X\n' % hi)
    print('bmfdata.S: %08X..%08X (%d bytes) from %s'
          % (lo, hi, hi - lo, ', '.join(s[0] for s in secs)))


if __name__ == '__main__':
    main()
